// <auto-generated />
namespace WhatsIn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initial_setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_setup));
        
        string IMigrationMetadata.Id
        {
            get { return "201801022009250_initial_setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
